[package]
name = "ifcap-rust"
version = "0.1.0"
authors = ["Rolph Recto <rolph.recto@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
im = "15.0.0"
matches = "0.1.8"
